[project]
name = "FTBQLocalizationTools"
version = "4.1.8"
description = "A small script to simplify your translation work."
requires-python = ">=3.12"
dependencies = [
    "nbt>=1.5.1",
    "snbtlib>=1.0.2",
]
